### ISSUE TITLE
Activity can't be blank

### ISSUE THREAD

**Issue by dcraggs** [SkyWriter/toggl#10]
Getting the error "Activity can't be blank" when doing the update.

Is activity a premium feature in Toggl?

**Comment by SkyWriter** [comment]
It's not a Toggl issue, but rather a Redmine misconfiguration. README mentions it:
> IMPORTANT: You should have default activity set in your Redmine.

Did you do that?

**Comment by dcraggs** [comment]
Thanks for the prompt reply.

I did see the comment but did not know where the setting was. A bit of googling and I found it in Administration/enumerations

May bed worth updating the Read Me.

Thanks

Dave
