### ISSUE TITLE
Multiple Redmines

### ISSUE THREAD

**Issue by dcraggs** [SkyWriter/toggl#11]
Would it be possible to have a configuration option so the the plugin can handle multiple redmines?

Some
thing like #A123 for one Redmine #B123 for a second and so on. So the plugin could optionally look for a non numeric value after the # key. 

Dave

**Comment by SkyWriter** [comment]
Thought it over a bit. It could be easily attained by adding a separate option for the plugin to match only those Toggl entries that match a certain regular expression.

Should be pretty easy to implement, but I don't have any particular plans on it. Might do it in my spare time. Pull requests are welcome though :)
