### ISSUE TITLE
redmine 3.1.0 support? 

### ISSUE THREAD

**Issue by AngieB** [SkyWriter/toggl#12]
Hi,
Just curious if this plugin will support 3.1.0 anytime soon? I've installed the toggl plugin to test it on the latest stable redmine 3.1.0, but the place to enter the toggl api key does not show within the redmine user account. 

thanks!

**Comment by SkyWriter** [comment]
Thanks for reporting, Angie. I'll look into it shortly.

**Comment by SkyWriter** [comment]
Thanks for reporting, Angie. I'll look into it shortly.

вс, 2 Авг 2015, 6:49, Angie <notifications@github.com>:

**Comment by AngieB** [comment]
Hi Ivan,

On further inspection, I believe the problem is related to a plugin migration issue on my redmine install. I was using a docker-passenger-redmine image and the volumes were not mounting correctly from host to guest. I'll be trying again today with a different docker image, and will report back.  

Thanks!

**Comment by SkyWriter** [comment]
Okay, so I went ahead and tested it on https://github.com/sameersbn/docker-redmine Redmine 3.1 Docker image. It all worked out fine.

Let me know if it works for you too in the end, so that I can add latest Redmine to the list of supported releases.

Here's my docker-compose.yml, if that helps (it is basically the same as what the author of the Redmine Docker image gives):

    postgresql:
      image: sameersbn/postgresql:9.4-2
      environment:
        - DB_USER=redmine
        - DB_PASS=password
        - DB_NAME=redmine_production
      volumes:
        - /tmp/postgresql:/var/lib/postgresql
    redmine:
      image: sameersbn/redmine:3.1.0
      links:
        - postgresql:postgresql
      environment:
        - TZ=Asia/Kolkata
        - REDMINE_PORT=10083
        - SMTP_ENABLED=false
        - SMTP_DOMAIN=www.example.com
        - SMTP_HOST=smtp.gmail.com
        - SMTP_PORT=587
        - SMTP_USER=mailer@example.com
        - SMTP_PASS=password
        - SMTP_STARTTLS=true
        - SMTP_AUTHENTICATION=:login
      ports:
        - "10083:80"
      volumes:
        - /tmp/redmine:/home/redmine/data

**Comment by AngieB** [comment]
It's working perfectly for me on Redmine 3.1.0 . Thanks!!!

**Comment by SkyWriter** [comment]
Awesome! Thank you for taking time to get it up and running.
