### ISSUE TITLE
Filtering by Project

### ISSUE THREAD

**Issue by michaljuris** [SkyWriter/toggl#15]
Would it be possible to also filter time records by project(pid)? Same way as it is possible to filter by work-spaces(wid)?

This would really help in case when different toggl projects are tracked with different tools (github, gitlab etc.) and we want to exclude to avoid conflicts

BTW: Thanks for this plugin!

**Comment by SkyWriter** [comment]
Glad that someone finds my work useful as well. I don't think that's something that's the plugin is capable of, but it's something that should be pretty straightforward to implement, and I'd gladly accept a pull request and aid the code review.
