### ISSUE TITLE
toggle with redmine 3.0.1.stable

### ISSUE THREAD

**Issue by nachocifu** [SkyWriter/toggl#8]
Trying to use this plugin with my redmine installation. Followed the steps and its now working. Not sure what im supposed to submit here so i leave my redmine enviroment.

Environment:
  Redmine version                3.0.1.stable
  Ruby version                   2.2.0-p0 (2014-12-25) [x86_64-linux]
  Rails version                  4.2.0
  Environment                    production
  Database adapter               Mysql2

**Comment by SkyWriter** [comment]
Hey there. A few questions:

1. Have the migrations went fine?
2. What does ```cd /path/to/redmine && RAILS_ENV=production bundle exec rake toggl:update``` output? Both when you have new Toggl entries and when you have none.

**Comment by nachocifu** [comment]
Hi, thanks for the quick response.
1.  only had trouble with the logs
...........redmine-3.0.1$ RAILS_ENV=production bundle exec rake redmine:plugins:migrate
Rails Error: Unable to access log file. Please ensure that /opt/redmine/redmine-3.0.1/log/production.log exists and is writable (ie, make it writable for user and group: chmod 0664 /opt/redmine/redmine-3.0.1/log/production.log). The log level has been raised to WARN and the output directed to STDERR until the problem is fixed.
Migrating toggl (Toggl plugin)...
  

2. same log error. I already added my toggl api key. in my toggle i have many entries, some with #xxx and some with just text

.................redmine-3.0.1$ RAILS_ENV=production bundle exec rake toggl:update
Rails Error: Unable to access log file. Please ensure that /opt/redmine/redmine-3.0.1/log/production.log exists and is writable (ie, make it writable for user and group: chmod 0664 /opt/redmine/redmine-3.0.1/log/production.log). The log level has been raised to WARN and the output directed to STDERR until the problem is fixed.

**Comment by SkyWriter** [comment]
So, does it work? Are the entries getting imported?

**Comment by nachocifu** [comment]
Nop :/
Any suggestion?

**Comment by SkyWriter** [comment]
I think I will just have to find a way to try this myself. It'd be very convenient if you arranged me access to the server, so I could take a look. If that is not an option, I'll setup my own copy of Redmine 3 and try. This will take more time though.

**Comment by nachocifu** [comment]
Not gonna be an option. No way my boss lets me. Do you mind sitting your copy?

**Comment by SkyWriter** [comment]
Sure. Will do so tomorrow. Didn't even know that Redmine 3 is out already, so now I want to try it myself anyway.

**Comment by SkyWriter** [comment]
Hey, by the way, do you have any activities present and default activity set in your Redmine? 

It's under http://redmine/enumerations and should look somewhat like this:
![2015-05-04 11 55 45](https://cloud.githubusercontent.com/assets/105392/7449281/9b14a2ee-f254-11e4-916a-350cc1f34604.png)

**Comment by SkyWriter** [comment]
I've also added verbose error message for the case of the failed import. Would you please pull in the latest master and try to do ``toggl:update`` once more?

    $ cd /path/to/redmine/plugins/toggl
    $ git pull origin master
    $ RAILS_ENV=production bundle exec rake toggl:update

**Comment by nachocifu** [comment]
its working!!! :) 
Honestly i feel embarrased, i forgot to set de default activity.....
its working now, wasnt necesary to update branch.
Thanks very much, its working great. Now il start searching for a plugin to change the format time is displayed. To get it more user friendly....
Hey, seriously, THANKS.!!!!!

**Comment by SkyWriter** [comment]
@nachocifu you're welcome :) Happy toggling!
